[package]
name = "deathclock-zk-methods"
version = "0.1.0"
edition = "2021"

[lib]
name = "deathclock_zk_methods"
path = "src/lib.rs"

[build-dependencies]
risc0-build = "3.0.6"

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
risc0-zkvm = { version = "3.0.6", default-features = false }
thiserror = "2"
