"use client";

import type { VaultSnapshot } from "@/types";
import { formatSol, stateLabel } from "@/utils/helpers";

type Props = { snapshot: VaultSnapshot; busy?: boolean; onReportDeath?: () => void; onInitiateChallenge?: () => void; onResolveChallenge?: (isAlive: boolean) => void; onRelease?: () => void };

export function InheritanceStatus({ snapshot, busy, onReportDeath, onInitiateChallenge, onResolveChallenge, onRelease }: Props) {
  const total = snapshot.balanceSol || 0;
  return <section className="rounded-[2rem] border border-ink/10 bg-acid p-6 sm:p-8"><p className="label text-ink/60">Inheritance status</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><h3 className="font-display text-3xl">{stateLabel(snapshot.state)}</h3><span className="text-sm font-semibold">{formatSol(total)} SOL protected</span></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-ink/10"><div className="h-full w-1/3 rounded-full bg-ink" /></div><div className="mt-3 flex justify-between text-[10px] font-bold uppercase tracking-[0.16em] text-ink/50"><span>Alive</span><span>Challenge</span><span>Release</span></div><p className="mt-8 max-w-xl text-sm leading-6 text-ink/70">A missed heartbeat opens a 48-hour challenge window. If no valid proof arrives, the estate is split by the shares you set.</p><div className="mt-6 flex flex-wrap gap-2">{snapshot.initialized && snapshot.state === "active" && onReportDeath && <button className="button-quiet border-ink/20" onClick={onReportDeath} disabled={busy}>Report missed heartbeat</button>}{snapshot.state === "missed" && onInitiateChallenge && <button className="button-primary bg-ink text-paper" onClick={onInitiateChallenge} disabled={busy}>Start 48h challenge</button>}{snapshot.state === "challenged" && onResolveChallenge && <><button className="button-quiet" onClick={() => onResolveChallenge(true)} disabled={busy}>I am alive</button><button className="button-primary bg-ink text-paper" onClick={() => onResolveChallenge(false)} disabled={busy}>Confirm release</button></>}{snapshot.state === "release" && onRelease && <button className="button-primary bg-ember text-white" onClick={onRelease} disabled={busy}>Distribute inheritance</button>}</div>{snapshot.heirs.length > 0 && <div className="mt-6 space-y-2">{snapshot.heirs.map((heir) => <div key={heir.address} className="flex justify-between border-t border-ink/10 pt-2 text-sm"><span className="font-mono text-xs">{heir.address}</span><strong>{heir.share}%</strong></div>)}</div>}</section>;
}
