[workspace]
members = [
    "programs/deathclock",
    "zk",
    "zk/methods",
    "vendor/risc0-solana/solana-verifier/programs/groth_16_verifier",
    "vendor/risc0-solana/solana-verifier/programs/verifier_router",
    "vendor/risc0-solana/solana-ownable/ownable",
    "vendor/risc0-solana/solana-ownable/ownable-macro",
]
exclude = ["zk/methods/guest"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
